/* Generated by the Systemtap dtrace wrapper */

static void __dtrace (void) __attribute__((unused));
static void __dtrace (void) {}

#include <sys/sdt.h>


#if defined STAP_SDT_V1
#define tokio_taskrun_semaphore taskrun_semaphore
#endif
#if defined STAP_SDT_V1 || defined STAP_SDT_V2 
__extension__ unsigned short tokio_taskrun_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#else
__extension__ unsigned short tokio_taskrun_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes"))) __attribute__ ((visibility ("hidden")));
#endif
